> household_power_consumption <- read.csv("C:/Users/monica/Desktop/household_power_consumption.txt", header=FALSE, sep=";", stringsAsFactors=TRUE)
>   View(household_power_consumption)
> sub_data <- household_power_consumption[household_power_consumption$Date %in% c("1/2/2007","2/2/2007") ,]
> date_time <- strptime(paste(sub_data$Date, sub_data$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 
> globalActivePower <- as.numeric(sub_data$Global_active_power)
> sub_Metering1 <- as.numeric(sub_data$Sub_metering_1)
> sub_Metering2 <- as.numeric(sub_data$Sub_metering_2)
> sub_Metering3 <- as.numeric(sub_data$Sub_metering_3)
> png("plot3.png", width=480, height=480)
> plot(date_time, sub_Metering1,xlim=c(0,30), ylim=c(0,30), type="l", ylab="Energy Submetering", xlab="")
> lines(date_time, sub_Metering2, type="l", col="red")
> lines(date_time, sub_Metering3, type="l", col="blue")
> legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
> dev.off()
